from hikari import Permissions

LOCALIZED_PERMISSIONS = {
    Permissions.CREATE_INSTANT_INVITE: "Создавать приглашение",
    Permissions.KICK_MEMBERS: "Выгонять пользователей",
    Permissions.BAN_MEMBERS: "Банить пользователей",
    Permissions.ADMINISTRATOR: "Администратор",
    Permissions.MANAGE_CHANNELS: "Управлять каналами",
    Permissions.MANAGE_GUILD: "Управлять гильдией",
    Permissions.ADD_REACTIONS: "Добавлять реакции",
    Permissions.VIEW_AUDIT_LOG: "Смотреть журнал аудита",
    Permissions.PRIORITY_SPEAKER: "Приоритетное вещание",
    Permissions.STREAM: "Стримить",
    Permissions.VIEW_CHANNEL: "Смотреть каналы",
    Permissions.SEND_MESSAGES: "Отправлять сообщения",
    Permissions.SEND_TTS_MESSAGES: "Отправлять TTS-сообщения",
    Permissions.MANAGE_MESSAGES: "Управлять сообщениями",
    Permissions.EMBED_LINKS: "Вложения",
    Permissions.ATTACH_FILES: "Прикреплять файлы",
    Permissions.READ_MESSAGE_HISTORY: "Читать историю сообщения",
    Permissions.MENTION_ROLES: "Упоминать роли",
    Permissions.USE_EXTERNAL_EMOJIS: "Использовать внешние эмодзи",
    Permissions.VIEW_GUILD_INSIGHTS: "Смотреть статистику гильдии",
    Permissions.CONNECT: "Присоединяться к голосовому каналу",
    Permissions.SPEAK: "Разговаривать",
    Permissions.MUTE_MEMBERS: "Выключить голос пользователю",
    Permissions.DEAFEN_MEMBERS: "Выключить слух пользователю",
    Permissions.MOVE_MEMBERS: "Перемещать пользователей",
    Permissions.USE_VOICE_ACTIVITY: "Использовать голосовую активность",
    Permissions.CHANGE_NICKNAME: "Изменять никнейм",
    Permissions.MANAGE_NICKNAMES: "Управлять никнейма",
    Permissions.MANAGE_ROLES: "Управлять ролями",
    Permissions.MANAGE_WEBHOOKS: "Управлять веб-хуками",
    Permissions.MANAGE_EMOJIS_AND_STICKERS: "Управлять эмодзи и стикерами",
    Permissions.USE_APPLICATION_COMMANDS: "Использовать приложения",
    Permissions.REQUEST_TO_SPEAK: "Выйти на сцену",
    Permissions.MANAGE_EVENTS: "Управлять событиями",
    Permissions.MANAGE_THREADS: "Управлять ветками",
    Permissions.CREATE_PUBLIC_THREADS: "Создавать публичные ветки",
    Permissions.CREATE_PRIVATE_THREADS: "Создавать приватные ветки",
    Permissions.USE_EXTERNAL_STICKERS: "Использовать внешние стикеры",
    Permissions.SEND_MESSAGES_IN_THREADS: "Отправлять сообщениях в ветках",
    Permissions.START_EMBEDDED_ACTIVITIES: "Начинать активности",
    Permissions.MODERATE_MEMBERS: "Модерировать участников",
    Permissions.VIEW_CREATOR_MONETIZATION_ANALYTICS: "Смотреть аналитику",
    Permissions.USE_SOUNDBOARD: "Использовать саунд-боард",
    Permissions.SEND_VOICE_MESSAGES: "Отправлять голосовые сообщения"
}
